#!/bin/bash
# Generates a .env file for account-manager.
#
# Standalone (local dev):
#   ./scripts/generate-env.sh
#
# Called by setup-pi.sh (Pi deployment):
#   ./scripts/generate-env.sh \
#     --env prod \
#     --port 3001 \
#     --hostname pi4.tail1234.ts.net \
#     --dev-prefix dev \
#     --client-id <uuid> \
#     --client-secret <hex> \
#     --output /opt/prod/account-manager/.env
#
# Flags:
#   --env           prod|dev          (default: development)
#   --port          PORT              (default: 3001)
#   --hostname      Tailscale hostname (default: localhost)
#   --dev-prefix    dev path prefix   (default: dev)
#   --gamebacklog-port  gamebacklog's PORT for localhost redirect URI (default: 3000)
#   --client-id     shared gamebacklog OAuth client ID (passed in, not generated)
#   --client-secret shared gamebacklog OAuth client secret (passed in, not generated)
#   --output        absolute path to write the .env to
#   --force         overwrite existing .env

set -e

# ── Defaults (local dev) ─────────────────────────────────────────────────────
ENV=development
PORT=3001
HOSTNAME=localhost
DEV_PREFIX=dev
GAMEBACKLOG_PORT=3000
CLIENT_ID=
CLIENT_SECRET=
OUTPUT=
FORCE=false

# ── Parse flags ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)           ENV="$2";           shift 2 ;;
    --port)          PORT="$2";          shift 2 ;;
    --hostname)      HOSTNAME="$2";      shift 2 ;;
    --dev-prefix)    DEV_PREFIX="$2";    shift 2 ;;
    --gamebacklog-port) GAMEBACKLOG_PORT="$2"; shift 2 ;;
    --client-id)     CLIENT_ID="$2";     shift 2 ;;
    --client-secret) CLIENT_SECRET="$2"; shift 2 ;;
    --output)        OUTPUT="$2";        shift 2 ;;
    --force)         FORCE=true;         shift   ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

# ── Resolve output path ───────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -n "$OUTPUT" ]]; then
  ENV_FILE="$OUTPUT"
else
  ENV_FILE="${SCRIPT_DIR}/../.env"
fi

if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" != "true" ]]; then
  echo ".env already exists at ${ENV_FILE}. Pass --force to overwrite." >&2
  exit 0
fi

# ── Derive environment-specific values ───────────────────────────────────────
if [[ "$HOSTNAME" == "localhost" ]]; then
  JWT_ISSUER="http://localhost:${PORT}"
  WEBAUTHN_RP_ID="localhost"
  WEBAUTHN_RP_NAME="Account Manager"
  GAMEBACKLOG_REDIRECT_URI="http://localhost:${GAMEBACKLOG_PORT}/auth/callback"
  DATA_DIR="./data"
elif [[ "$ENV" == "production" || "$ENV" == "prod" ]]; then
  JWT_ISSUER="https://${HOSTNAME}/account-manager"
  WEBAUTHN_RP_ID="${HOSTNAME}"
  WEBAUTHN_RP_NAME="Account Manager"
  GAMEBACKLOG_REDIRECT_URI="https://${HOSTNAME}/gamebacklog/auth/callback"
  DATA_DIR="/var/lib/account-manager-prod"
else
  JWT_ISSUER="https://${HOSTNAME}/${DEV_PREFIX}/account-manager"
  WEBAUTHN_RP_ID="${HOSTNAME}"
  WEBAUTHN_RP_NAME="Account Manager (dev)"
  GAMEBACKLOG_REDIRECT_URI="https://${HOSTNAME}/${DEV_PREFIX}/gamebacklog/auth/callback"
  DATA_DIR="/var/lib/account-manager-dev"
fi

# ── Generate secrets ─────────────────────────────────────────────────────────
gen_hex() { openssl rand -hex "$1"; }
gen_uuid() { python3 -c "import uuid; print(uuid.uuid4())"; }

CSRF_SECRET="$(gen_hex 32)"
[[ -z "$CLIENT_ID" ]]     && CLIENT_ID="$(gen_uuid)"
[[ -z "$CLIENT_SECRET" ]] && CLIENT_SECRET="$(gen_hex 32)"

# ── Write .env ───────────────────────────────────────────────────────────────
cat > "$ENV_FILE" << EOF
# Generated by scripts/generate-env.sh on $(date)
# NEVER commit this file to git.

PORT=${PORT}
NODE_ENV=${ENV}
DATA_DIR=${DATA_DIR}

# Strong random secret for CSRF protection
CSRF_SECRET=${CSRF_SECRET}

# Must match the issuer claim in issued JWTs; relying parties verify against this
JWT_ISSUER=${JWT_ISSUER}

# WebAuthn relying party — must match the server's domain/IP
WEBAUTHN_RP_ID=${WEBAUTHN_RP_ID}
WEBAUTHN_RP_NAME=${WEBAUTHN_RP_NAME}

# Game Backlog OAuth client registered in this service's DB.
# GAMEBACKLOG_CLIENT_ID and GAMEBACKLOG_CLIENT_SECRET must match the values
# in gamebacklog's .env exactly.
GAMEBACKLOG_CLIENT_ID=${CLIENT_ID}
GAMEBACKLOG_CLIENT_SECRET=${CLIENT_SECRET}
GAMEBACKLOG_REDIRECT_URI=${GAMEBACKLOG_REDIRECT_URI}
EOF

echo ".env written to ${ENV_FILE}"
echo ""
echo "Shared values (copy these to gamebacklog's .env):"
echo "  GAMEBACKLOG_CLIENT_ID=${CLIENT_ID}"
echo "  GAMEBACKLOG_CLIENT_SECRET=${CLIENT_SECRET}"
echo "  GAMEBACKLOG_REDIRECT_URI=${GAMEBACKLOG_REDIRECT_URI}"
